spring.application.name=devspace
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/devspace_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update